apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: consul
  labels:
    app: dnsutils
spec:
  containers:
  - name: dnsutils
    image: byrnedo/alpine-curl
    command:
      - "/bin/sh"
      - "-c"
      - "while true; do sleep 3600; done"
    imagePullPolicy: IfNotPresent
