apiVersion: v1
data:
  token: MDU3MWIyZjQtNWMwZS1mYmI4LTZmZDAtMmFlYTY4NzljMWFj
kind: Secret
metadata:
  creationTimestamp: "2024-05-22T17:38:27Z"
  labels:
    managed-by: consul-k8s
  name: consul-partitions-acl-token
  namespace: consul
  resourceVersion: "6061115"
  uid: 528b7b8e-e797-4314-8547-40a0388c0f2a
type: Opaque
