---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
  namespace: tgw
# Allow traffic from nginx to frontend
spec:
  destination:
    name: frontend
  sources:
    - name: nginx
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: public-api
  namespace: tgw
# Allow traffic from nginx to public-api
spec:
  destination:
    name: public-api
  sources:
    - name: nginx
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product-api
  namespace: tgw
# Allow traffic from public-api to product-api
spec:
  destination:
    name: product-api
  sources:
    - name: public-api
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
  namespace: tgw
# Allow traffic from public-api to payments
spec:
  destination:
    name: payments
  sources:
    - name: public-api
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-gateway
# Allow traffic from api-gateway and traffic-generator to nginx
spec:
  destination:
    name: nginx
  sources:
    - name: api-gateway
      action: allow
    - name: traffic-generator
      action: allow