---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: fakeservice
# Allow traffic from api-gateway to nginx
spec:
  destination:
    name: web
    namespace: fakeservice
  sources:
    - name: api-gateway
      namespace: api-gateway
      action: allow