apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - certificate.yaml  # Include the certificate resource

helmCharts:
  - name: falco
    repo: https://falcosecurity.github.io/charts
    releaseName: falco
    namespace: falco
    version: "<enter chart version here>"  # Specify the version of the chart if needed
    valuesInline:
      falcosidekick:
        enabled: true
        webui:
          enabled: true
      tty: true

patchesStrategicMerge:
  - ingress.yaml




