apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ping
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        access_log /var/log/nginx/access.log main;
        sendfile on;
        keepalive_timeout 65;

        server {
            listen 80;
            server_name www.maniak.lab;

            location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
            }

            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fooservice-deployment
  namespace: ping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fooservice
  template:
    metadata:
      labels:
        app: fooservice
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: fooservice
  namespace: ping
spec:
  type: ClusterIP
  selector:
    app: fooservice
  ports:
  - port: 80
    targetPort: 80

