controller:
  service:
    enabled: true
    type: NodePort
    nodePorts:
      http: 30080
      https: 31443
  extraArgs:
    enable-ssl-passthrough: "true"
  watchIngressWithoutClass: true
  admissionWebhooks: 
   patch:
      enabled: true