global:
  enabled: false
  logLevel: "debug"
  name: dataplane
  datacenter: k8s01
  image: "hashicorp/consul-enterprise:1.18.1-ent"
  imageK8S: docker.mirror.hashicorp.services/hashicorp/consul-k8s-control-plane:1.4.1
  #imageConsulDataplane: "hashicorp/consul-dataplane:1.0.0"
  enterpriseLicense:
    secretName: 'consul-ent-license'
    secretKey: 'key'
    enableLicenseAutoload: true


  enableConsulNamespaces: true
  adminPartitions:
    enabled: true
    name: shared
  peering:
    enabled: true
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-acl-token
      secretKey: token

  tls:
    enabled: true
    httpsOnly: false  # Metrics are exposed on 8500 only (http).  Anonymous policy requires Agent "read" if ACL enabled.
    caCert:
      secretName: consul-bootstrap-acl-token
      secretKey: tls.crt

externalServers:
  enabled: true
  hosts: ["172.16.10.200"]
  tlsServerName: "server.mk1.consul"
  httpsPort: 443
  grpcPort: 8502
  useSystemRoots: true
  k8sAuthMethodHost: https://172.16.10.23:6443

dns:
  enabled: true
  enableRedirection: true

server:
  enabled: false

connectInject:
  consulNamespaces:
    consulDestinationNamespace: "default"   # Ignored when mirroringK8S is true
    mirroringK8S: true
  transparentProxy:
    defaultEnabled: true
  enabled: true
  default: false
  # consulNode:
  #   meta: 
  #     node: "maniak-shared-usw2new-agentless-node"
  cni:
    enabled: true

#controller:
#  enabled: true

meshGateway:
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: ClusterIP
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#lb-type
    # annotations: |
    #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"

# ingressGateways:
#   enabled: true
#   defaults:
#     replicas: 1
#   gateways:
#     - name: ingress-gateway
#       service:
#         type: LoadBalancer
#         annotations: |
#           service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"