---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-gateway
  namespace: hashicups
# Allow traffic from api-gateway to nginx
spec:
  destination:
    name: web
  sources:
    - name: api-gateway
      action: allow