apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-server
  namespace: consul
spec:
  secretName: test-server-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  - "consul.maniak.lab"
  issuerRef:
    name: test-ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-client
  namespace: consul
spec:
  secretName: test-client-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  - "consul.maniak.lab"
  issuerRef:
    name: test-ca-issuer